import { useState } from 'react'
import { LABELS, VOCABULARY } from './data'
import { blindCandidateAdapter, canEditInitial, canEditUnion, createLocalId, exportRows, geometryToPercentRect, loadState, persistState, refineCandidate, rowsToCsv, unionMemberCount, viewerDragToGeometry } from './store'
import type { AppState, BlindCandidate, Geometry, Relevance, Role, Roi, Slide } from './types'

type View = 'queue'|'initial'|'union'|'admin'|'qc'
const relevances: [Relevance,string][] = [['none','无'],['weak','弱'],['moderate','中等'],['strong','强']]
const stamp = () => new Date().toLocaleString('zh-CN', { hour12:false })
function download(name:string, data:string, type:string) { const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([data],{type})); a.download=name; a.click(); URL.revokeObjectURL(a.href) }

export function App() {
  const [state, setState] = useState<AppState>(loadState)
  const [role, setRole] = useState<Role>('pathologist')
  const [view,setView] = useState<View>('queue')
  const [activeCase,setActiveCase] = useState('CASE-017')
  const [toast,setToast] = useState('')
  const change=(updater:(s:AppState)=>AppState, note?:string) => { setState(old=>{ const next=updater(old); persistState(next); return next }); if(note) { setToast(note); window.setTimeout(()=>setToast(''),2800) } }
  const audit=(s:AppState,action:string,detail:string):AppState => ({...s,audits:[{id:createLocalId(),at:new Date().toISOString(),actor:role==='admin'?'管理员 A01':role==='adjudicator'?'裁决者 P002':'病理医师 P001',action,detail},...s.audits]})
  const current = state.cases.find(c=>c.id===activeCase)!
  const currentSlide = state.slides.find(slide=>slide.id===current.slideId) ?? state.slides[0]
  const nav: [View,string,Role[]][] = [['queue','任务队列',['pathologist','adjudicator','admin']],['initial','初始 ROI',['pathologist','admin']],['union','盲法裁决',['adjudicator','admin']],['admin','研究管理',['admin']],['qc','质控与导出',['admin']]]
  return <div className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">PE</span><div><strong>Pathology Evidence</strong><small>Annotation Workstation · protocol v1.0</small></div></div><div className="top-actions"><span className="connection"><i/> 本地演示数据已保存</span><label className="role-select">演示身份 <select value={role} onChange={e=>{setRole(e.target.value as Role);setView('queue')}}><option value="pathologist">病理医师 P001</option><option value="adjudicator">盲法裁决者 P002</option><option value="admin">研究管理员 A01</option></select></label></div></header>
    <div className="workspace"><aside className="sidebar"><div className="profile"><div className="avatar">{role==='admin'?'A':'P'}</div><div><b>{role==='admin'?'管理员 A01':role==='adjudicator'?'裁决者 P002':'病理医师 P001'}</b><small>{role==='admin'?'Study administrator':role==='adjudicator'?'Blind reviewer':'Initial evidence reviewer'}</small></div></div><nav>{nav.filter(n=>n[2].includes(role)).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{icon(id)}<span>{label}</span></button>)}</nav><div className="protocol"><b>当前协议</b><span>Evidence Test v1</span><small>词表 v1 · Union seed 已锁定</small></div></aside>
    <main>{view==='queue'&&<Queue state={state} role={role} open={(id,stage)=>{setActiveCase(id);setView(stage)}}/>}{view==='initial'&&<Initial state={state} current={current} slide={currentSlide} change={change} audit={audit}/>} {view==='union'&&<Union state={state} current={current} slide={currentSlide} change={change} audit={audit}/>} {view==='admin'&&<Admin state={state} change={change} audit={audit}/>} {view==='qc'&&<QC state={state}/>}</main></div>{toast&&<div className="toast">✓ {toast}</div>}</div>
}
function icon(id:string) { return <span className="nav-icon">{{queue:'▦',initial:'⌑',union:'◈',admin:'⚙',qc:'▤'}[id]}</span> }

function Queue({state,role,open}:{state:AppState;role:Role;open:(id:string,stage:View)=>void}) {
  const union=role==='adjudicator'
  const rows=state.cases.filter(c=>union ? c.unionStatus==='active' : c.assignee==='P001')
  return <section className="page"><div className="page-title"><div><p className="eyebrow">MY ASSIGNMENTS</p><h1>{union?'盲法 Union 裁决队列':'我的标注任务'}</h1><p>{union?'候选 ROI 的来源、方法与生成信息均不可见。':'为每个病例选择 1–5 个最具诊断价值的代表性区域。'}</p></div><div className="stat-chip">{rows.length} 项待处理</div></div><div className="study-strip"><div><b>Evidence Test v1</b><span>研究状态：{union?'Union adjudication':'Initial expert ROI'}</span></div><div><span className="status-dot"/> {union?'固定盲序列 · seed: study-2026-evidence-v1':'Reference diagnosis 已开放'}</div></div><div className="task-table"><div className="task-head"><span>病例</span><span>参考诊断</span><span>阶段</span><span>状态</span><span/></div>{rows.map((c,i)=>{ const status=union ? '待裁决' : c.initialStatus==='submitted' ? '已提交' : '进行中'; return <div className="task-row" key={c.id}><div><b>{c.id}</b><small>{c.title} · {c.slideId}</small></div><span>{union?'—':c.referenceDiagnosis}</span><span>{union?'盲法候选裁决':'Initial Expert ROI'}</span><span className={`badge ${union?c.unionStatus:c.initialStatus}`}>{status}</span><button className="primary compact" onClick={()=>open(c.id,union?'union':'initial')}>{union?`继续 · ${i+1}/3`:'打开病例'} →</button></div>})}</div><section className="instruction"><b>本阶段说明</b><p>{union?'请判断当前高亮候选 ROI 的可评价性、诊断价值与形态学证据。仅可微调当前 ROI；不能新建 ROI。':'请在全片上下文中主动定位证据。提交后病例进入只读状态，研究管理员冻结轮次后不可再编辑。'}</p></section></section>
}

function SlideViewer({slide,roi,onGeometry,locked,union}:{slide:Slide;roi?:Pick<Roi,'geometry'>;onGeometry?:(g:Geometry)=>void;locked?:boolean;union?:boolean}) { const [zoom,setZoom]=useState(7.5); const [pan,setPan]=useState(0); const [drag,setDrag]=useState<{x:number;y:number}|null>(null); const [draft,setDraft]=useState<Geometry|undefined>(); const shown=draft??roi?.geometry
  const point=(event:React.MouseEvent<HTMLDivElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return {x:(event.clientX-rect.left)/rect.width,y:(event.clientY-rect.top)/rect.height}}
  const down=(e:React.MouseEvent<HTMLDivElement>)=>{ if(locked||union||!onGeometry) return; setDrag(point(e)) }
  const move=(e:React.MouseEvent<HTMLDivElement>)=>{if(!drag||!onGeometry)return;setDraft(viewerDragToGeometry(drag,point(e),slide))}
  const up=(e:React.MouseEvent<HTMLDivElement>)=>{ if(drag&&onGeometry) onGeometry(viewerDragToGeometry(drag,point(e),slide));setDraft(undefined);setDrag(null) }
  const css=shown?geometryToPercentRect(shown,slide):undefined
  const viewerStyle={backgroundPosition:`${50+pan}% 50%`,backgroundImage:`url('${slide.imageUrl}')`}
  return <div className="viewer-card"><div className="viewer-toolbar"><span>{slide.id}.svs · {slide.widthLevel0} × {slide.heightLevel0}</span><div><button onClick={()=>setPan(pan-5)}>←</button><button onClick={()=>setPan(pan+5)}>→</button><button onClick={()=>setZoom(z=>Math.max(2,z-1))}>−</button><b>{zoom.toFixed(1)}×</b><button onClick={()=>setZoom(z=>z+1)}>＋</button></div></div><div className="viewer" onMouseDown={down} onMouseMove={move} onMouseUp={up} style={viewerStyle}><div className="slide-texture"/><div className="crypt crypt-a"/><div className="crypt crypt-b"/><div className="crypt crypt-c"/>{shown&&<div className={`roi-box ${union?'blind-focus':''}`} style={css}><span>{union?'当前候选':'ROI'}</span></div>}<div className="scale"><i/> 500 μm</div>{!roi&&!locked&&<div className="draw-hint">在视野中拖拽绘制矩形 ROI</div>}</div><div className="overview" style={{backgroundImage:`url('${slide.imageUrl}')`}}><span className="mini-area"/></div></div> }

function EvidenceForm({roi,onChange,mode,locked}:{roi:Roi|BlindCandidate;onChange:(patch:Partial<Roi>)=>void;mode:'initial'|'union';locked:boolean}) { const toggle=(value:string,arr:string[])=>onChange({evidence:arr.includes(value)?arr.filter(x=>x!==value):[...arr,value]}); return <aside className="form-panel"><div className="panel-heading"><div><p className="eyebrow">{mode==='union'?'BLIND EVIDENCE REVIEW':'EVIDENCE ANNOTATION'}</p><h2>{mode==='union'?'候选裁决':'当前 ROI'}</h2></div><span className={locked?'lock-label':'draft-label'}>{locked?'已冻结':'草稿'}</span></div>{mode==='initial'&&<div className="form-note">这是一项 evidence annotation：请记录支持参考诊断的形态学证据。</div>}<Question title="Q1 · 是否可评价？"><div className="segmented">{[['yes','可评价'],['no','不可评价']].map(([v,l])=><button disabled={locked} className={(roi.evaluable===(v==='yes'))?'selected':''} onClick={()=>onChange({evaluable:v==='yes'})}>{l}</button>)}</div></Question><Question title="Q2 · 诊断价值"><div className="radio-grid">{relevances.map(([v,l])=><label key={v}><input disabled={locked} type="radio" checked={roi.relevance===v} onChange={()=>onChange({relevance:v})}/>{l}</label>)}</div></Question><Question title="Q3 · Morphology（多选）"><div className="tag-list">{VOCABULARY.map(([group,items])=><div key={group}><small>{group}</small>{items.map(v=><label className="check" key={v}><input disabled={locked} type="checkbox" checked={roi.evidence.includes(v)} onChange={()=>toggle(v,roi.evidence)}/>{LABELS[v]}</label>)}</div>)}</div></Question><Question title="Q4 · 支持的诊断"><div className="diagnoses">{['HP','SSL','TSA','TA','TVA','non-specific'].map(d=><label key={d}><input disabled={locked} type="checkbox" checked={roi.supports.includes(d)} onChange={()=>onChange({supports:roi.supports.includes(d)?roi.supports.filter(x=>x!==d):[...roi.supports,d]})}/>{d}</label>)}</div></Question>{mode==='union'&&<><Question title="Q5 · 与病例参考诊断一致？"><div className="segmented three">{[['supports','支持'],['neutral','中性'],['contradicts','矛盾']].map(([v,l])=><button disabled={locked} className={roi.consistency===v?'selected':''} onClick={()=>onChange({consistency:v as Roi['consistency']})}>{l}</button>)}</div></Question><Question title="Q6 · HGD evidence"><select disabled={locked} value={roi.hgd} onChange={e=>onChange({hgd:e.target.value as Roi['hgd']})}><option value="present">存在</option><option value="absent">缺如</option><option value="not_assessable">不可评估</option><option value="not_relevant">不适用</option></select></Question></>}<div className="revision">版本 {roi.revision} · {roi.originalGeometry?'保留原始几何':'原始几何未变更'}<br/><small>最后编辑：{stamp()}</small></div></aside> }
function Question({title,children}:{title:string;children:React.ReactNode}) {return <div className="question"><h3>{title}</h3>{children}</div>}

function Initial({state,current,slide,change,audit}:{state:AppState;current:any;slide:Slide;change:any;audit:any}) {
  const rois=state.rois.filter(r=>r.caseId===current.id&&r.sourceType==='expert_initial')
  const [selected,setSelected]=useState(rois[0]?.id)
  const selectedRoi=state.rois.find(r=>r.id===selected)
  const locked=!canEditInitial(state)||current.initialStatus==='submitted'
  const edit=(patch:Partial<Roi>)=>change((s:AppState)=>({...s,rois:s.rois.map(r=>r.id===selected ? {...r,...patch,modifiedAt:new Date().toISOString()} : r)}),'草稿已保存')
  const add=()=>{if(locked||rois.length>=5)return;const id=`ROI-E-${current.id.slice(-3)}-${String(rois.length+1).padStart(2,'0')}`; const geometry={x:2800,y:2200,width:850,height:650}; const r:Roi={id,caseId:current.id,slideId:current.slideId,geometry,physicalWidthUm:geometry.width*slide.mppX,physicalHeightUm:geometry.height*slide.mppY,evidence:[],relevance:'none',evaluable:true,supports:[],consistency:'neutral',hgd:'not_relevant',revision:1,status:'draft',createdAt:new Date().toISOString(),modifiedAt:new Date().toISOString(),sourceType:'expert_initial'};change((s:AppState)=>audit({...s,rois:[...s.rois,r]},'创建 ROI',`${current.id} · ${id}`),'已新增 ROI');setSelected(id)}
  const submit=()=>change((s:AppState)=>audit({...s,cases:s.cases.map((c:typeof current)=>c.id===current.id?{...c,initialStatus:'submitted'}:c),rois:s.rois.map((r:Roi)=>r.caseId===current.id&&r.sourceType==='expert_initial'?{...r,status:'submitted'}:r)},'提交初始标注',`${current.id} · ${rois.length} 个 ROI`),'病例已提交，现为只读')
  return <section className="work-page"><div className="casebar"><div><p className="eyebrow">INITIAL EXPERT ROI</p><h1>{current.id} <span>{current.title}</span></h1></div><div className="case-meta"><span>Reference: <b>{current.referenceDiagnosis}</b></span><span>HGD: <b>{current.hgd}</b></span><span>ROI: <b>{rois.length}/5</b></span></div></div><div className="annotate-grid"><div className="slide-column"><SlideViewer slide={slide} roi={selectedRoi} locked={locked} onGeometry={g=>selected&&edit({geometry:g,physicalWidthUm:g.width*slide.mppX,physicalHeightUm:g.height*slide.mppY})}/><div className="roi-tray">{rois.map((r,i)=><button className={selected===r.id?'selected':''} onClick={()=>setSelected(r.id)} key={r.id}><b>ROI {i+1}</b><span>{r.evidence[0]?LABELS[r.evidence[0]]:'待标记'}</span></button>)}<button className="add-roi" disabled={locked||rois.length>=5} onClick={add}>＋ 添加 ROI</button></div></div>{selectedRoi?<EvidenceForm roi={selectedRoi} onChange={edit} mode="initial" locked={locked}/>:<div className="empty-panel">请添加第一个 ROI</div>}</div><footer className="action-footer"><span>{locked?'此病例已提交；如需变更，请由管理员创建修订轮次。':'提交前可随时修改草稿。'}</span><button className="primary" disabled={locked||rois.length<1} onClick={submit}>提交初始标注并锁定</button></footer></section>
}

function Union({state,current,slide,change,audit}:{state:AppState;current:any;slide:Slide;change:any;audit:any}) { const candidates=state.rois.filter(r=>r.caseId===current.id&&Boolean(r.blindId)); const [index,setIndex]=useState(0); const sourceRoi=candidates[index]; const roi=sourceRoi&&blindCandidateAdapter(sourceRoi); const locked=!canEditUnion(state); if(!roi||!sourceRoi)return <section className="page">当前病例尚无可裁决的盲法候选。</section>; const update=(patch:Partial<Roi>)=>change((s:AppState)=>({...s,rois:s.rois.map((r:Roi)=>r.id===sourceRoi.id?{...r,...patch,modifiedAt:new Date().toISOString()}:r)}),'裁决草稿已保存'); const refine=()=>{if(locked)return;const g={...roi.geometry,x:roi.geometry.x+160,y:roi.geometry.y+90};change((s:AppState)=>audit({...s,rois:s.rois.map((r:Roi)=>r.id===sourceRoi.id?refineCandidate(r,g):r)},'微调盲法候选',`${current.id} · ${roi.blindId}，原始几何已保留`),'已创建几何修订（原始位置已保留）')}; const next=()=>{change((s:AppState)=>audit({...s,rois:s.rois.map((r:Roi)=>r.id===sourceRoi.id?{...r,status:'submitted'}:r)},'提交盲法裁决',`${current.id} · ${roi.blindId}`),'当前候选已提交');setIndex(i=>Math.min(candidates.length-1,i+1))}; return <section className="work-page"><div className="casebar"><div><p className="eyebrow">BLIND UNION ADJUDICATION</p><h1>{current.id} <span>Candidate {String(index+1).padStart(2,'0')} / {candidates.length}</span></h1></div><div className="blind-banner">◉ 固定盲 ID · 随机顺序已锁定 · 来源不可见</div></div><div className="annotate-grid"><div className="slide-column"><SlideViewer slide={slide} roi={roi} union/><div className="blind-controls"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}>← 上一条</button><button disabled={locked} className="outline" onClick={refine}>◇ 微调当前 ROI</button><small>不能新增 ROI；微调会保留 original geometry。</small></div></div><EvidenceForm roi={roi} onChange={update} mode="union" locked={locked}/></div><footer className="action-footer"><span>当前候选：{roi.status==='submitted'?'已提交':'草稿'} · 所有答题均按盲法候选保存</span><button className="primary" disabled={locked} onClick={next}>{index===candidates.length-1?'提交完成':'提交并进入下一条'} →</button></footer></section> }

function Admin({state,change,audit}:{state:AppState;change:any;audit:any}) { const freeze=(round:'initial'|'union')=>change((s:AppState)=>audit({...s,round:{...s.round,[round]:'frozen'}},'冻结标注轮次',`${round==='initial'?'Initial Expert ROI':'Union Adjudication'} 已冻结`),`${round==='initial'?'Initial':'Union'} round 已冻结，所有历史记录保持只读`); const action=(name:string,detail:string)=>change((s:AppState)=>audit(s,name,detail),`${name}：${detail}`); const initDone=state.cases.filter(c=>c.initialStatus==='submitted').length; const unionDone=state.cases.filter(c=>c.unionStatus==='submitted').length; const unions=state.rois.filter(r=>r.blindId); return <section className="page"><div className="page-title"><div><p className="eyebrow">ADMIN STUDY MANAGER</p><h1>Evidence Test v1</h1><p>实验状态、冻结边界与后续队列操作。</p></div><span className="protocol-badge">protocol v1.0 · vocab v1</span></div><div className="metric-grid"><Metric n={`${initDone}/${state.cases.length}`} label="Initial complete"/><Metric n="4/4" label="Fixed runs"/><Metric n="4/4" label="Agent runs"/><Metric n={`${unionDone}/${state.cases.length}`} label="Finalized"/></div><div className="admin-grid"><section className="manager-card"><h2>阶段控制</h2><div className="stage-row"><div><b>A · Initial Expert ROI</b><span>{state.round.initial==='frozen'?'FROZEN':'ACTIVE'} · {initDone}/{state.cases.length} cases</span></div><button className="danger" disabled={state.round.initial==='frozen'} onClick={()=>freeze('initial')}>冻结 Round</button></div><div className="stage-row"><div><b>B · Union Blind Adjudication</b><span>{state.round.union==='frozen'?'FROZEN':'ACTIVE'} · {unionDone}/{state.cases.length} cases</span></div><button className="danger" disabled={state.round.union==='frozen'} onClick={()=>freeze('union')}>冻结 Round</button></div><p className="small-note">冻结后不覆盖原始 annotation；后续改动必须产生 revision / supersedes 记录。</p></section><section className="manager-card"><h2>受控操作</h2><div className="admin-actions"><button onClick={()=>action('生成 Union','保留成员 provenance，使用 IoU ≥ 0.50 去重')}>生成 Union</button><button onClick={()=>action('分配病例','已分配 P001 / P002，盲序列固定')}>分配病例</button><button onClick={()=>action('准备导出','Export bundle 已记录版本和审计摘要')}>准备 Export</button></div><p className="small-note">盲法 API adapter 仅返回 candidate geometry 与裁决字段；source_type 永不下发至 adjudicator。</p></section></div><section className="audit-card"><h2>Union 去重概览（管理员）</h2>{unions.map(candidate=><div className="audit" key={candidate.id}><time>{candidate.blindId}</time><b>{candidate.id}</b><span>{unionMemberCount(state,candidate.id)} 个保留成员</span><small>成员来源仅在管理员导出中解盲</small></div>)}</section><section className="audit-card"><h2>审计日志</h2>{state.audits.slice(0,7).map(a=><div className="audit" key={a.id}><time>{new Date(a.at).toLocaleString('zh-CN',{hour12:false})}</time><b>{a.actor}</b><span>{a.action}</span><small>{a.detail}</small></div>)}</section></section> }
function Metric({n,label}:{n:string;label:string}) {return <div className="metric"><b>{n}</b><span>{label}</span></div>}

function QC({state}:{state:AppState}) { const valid=state.rois.filter(r=>r.evaluable&&r.relevance!=='none').length; const revisions=state.rois.filter(r=>r.originalGeometry).length; const unionCandidates=state.rois.filter(r=>r.blindId); const runExport=(format:'json'|'csv')=>{const rows=exportRows(state);if(format==='json')download('evidence-export-v1.json',JSON.stringify({protocol:'v1.0',exportedAt:new Date().toISOString(),rows},null,2),'application/json');else download('evidence-export-v1.csv',rowsToCsv(rows),'text/csv')}; return <section className="page"><div className="page-title"><div><p className="eyebrow">QC & EXPORT</p><h1>质量控制与导出</h1><p>仅管理员可在此处关联 candidate provenance；导出中保留版本与审计追踪。</p></div></div><div className="metric-grid"><Metric n={`${valid}/${state.rois.length}`} label="有效 evidence"/><Metric n="2" label="待复核冲突"/><Metric n={`${revisions}`} label="geometry revisions"/><Metric n={`${state.audits.length}`} label="audit events"/></div><div className="qc-grid"><section className="conflicts"><h2>需要处理的冲突</h2><div className="conflict"><b>CASE-021 · U-04</b><span>P001: Strong SSL · P002: non-specific</span><button>查看审计</button></div><div className="conflict"><b>CASE-039 · U-02</b><span>HGD: present / not assessable</span><button>指派第三阅片者</button></div></section><section className="export"><h2>受控导出</h2><p>JSON 包含完整 geometry、revision、每个 union candidate 的保留 members/provenance；CSV 适合表格分析。</p><p className="small-note">本轮 {unionCandidates.length} 个去重候选，共保留 {state.unionMembers.length} 条成员关系。</p><div><button className="primary" onClick={()=>runExport('json')}>↓ 导出 JSON</button><button onClick={()=>runExport('csv')}>↓ 导出 CSV</button></div><small>Export schema: roi_id, blind_id, geometry, evidence, members, source_type, revision</small></section></div><section className="audit-card"><h2>最近审计记录</h2>{state.audits.slice(0,10).map(a=><div className="audit" key={a.id}><time>{new Date(a.at).toLocaleString('zh-CN',{hour12:false})}</time><b>{a.actor}</b><span>{a.action}</span><small>{a.detail}</small></div>)}</section></section> }
